services:

  selenium-hub:
    image: selenium/hub:4.21.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.21.0
    container_name: chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

  firefox:
    image: selenium/node-firefox:4.21.0
    container_name: firefox
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

  video-chrome:
    image: selenium/video:latest
    depends_on:
      - chrome
    shm_size: 2gb
    environment:
      DISPLAY_CONTAINER_NAME: chrome
      SE_VIDEO_FILE_NAME: auto
    volumes:
      - ./Reports/Videos:/videos

  video-firefox:
    image: selenium/video:latest
    depends_on:
      - firefox
    shm_size: 2gb
    environment:
      DISPLAY_CONTAINER_NAME: firefox
      SE_VIDEO_FILE_NAME: auto
    volumes:
      - ./Reports/Videos:/videos