env: qa
browser: chrome
grid_url: http://localhost:4444/wd/hub

environments:
  dev:
    ui_base_url: https://automationexercise.com
    api_base_url: https://dummyjson.com

  qa:
    ui_base_url: https://automationexercise.com
    api_base_url: https://dummyjson.com

  stage:
    ui_base_url: https://automationexercise.com
    api_base_url: https://dummyjson.com
